# Generated by Django 3.2 on 2021-04-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkcountrylanguage',
            name='id_country',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='linkcountrylanguage',
            name='id_language',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
